//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalLifeSettings.Storage {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class KeyBindings : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyBindings defaultInstance = ((KeyBindings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyBindings())));
        
        public static KeyBindings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::System.Windows.Forms.Keys InGameMenu {
            get {
                return ((global::System.Windows.Forms.Keys)(this["InGameMenu"]));
            }
            set {
                this["InGameMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys ScreenUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ScreenUp"]));
            }
            set {
                this["ScreenUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys ScreenDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ScreenDown"]));
            }
            set {
                this["ScreenDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys ScreenLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ScreenLeft"]));
            }
            set {
                this["ScreenLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys ScreenRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ScreenRight"]));
            }
            set {
                this["ScreenRight"] = value;
            }
        }
    }
}
