//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLDedicatedServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DedicatedServer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DedicatedServer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLDedicatedServer.Properties.DedicatedServer", typeof(DedicatedServer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Connected.
        /// </summary>
        public static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Disconnected.
        /// </summary>
        public static string ClientDisconnected {
            get {
                return ResourceManager.GetString("ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found!.
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying module names. For help on individual commands in a module, do \&quot;(modulename) help\&quot;.
        /// </summary>
        public static string DisplayCommandNames {
            get {
                return ResourceManager.GetString("DisplayCommandNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Started.
        /// </summary>
        public static string GameStarted {
            get {
                return ResourceManager.GetString("GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating World!.
        /// </summary>
        public static string GeneratingWorld {
            get {
                return ResourceManager.GetString("GeneratingWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing networking!.
        /// </summary>
        public static string InitializingNetwork {
            get {
                return ResourceManager.GetString("InitializingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command parameters.
        /// </summary>
        public static string InvalidCommandParameters {
            get {
                return ResourceManager.GetString("InvalidCommandParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing names of commands within the specified module. For detailed command information, do \&quot;(modulename) (commandname) help\.
        /// </summary>
        public static string ListCommands {
            get {
                return ResourceManager.GetString("ListCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical Life.
        /// </summary>
        public static string MagicalLife {
            get {
                return ResourceManager.GetString("MagicalLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new world and hosts a new game\r\n Usage: ml newgame (mygamenamehere).
        /// </summary>
        public static string NewGameCommandDesc {
            get {
                return ResourceManager.GetString("NewGameCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the game to disk.
        /// </summary>
        public static string SaveGameCommandDesc {
            get {
                return ResourceManager.GetString("SaveGameCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the game.
        /// </summary>
        public static string StartGameCommandDesc {
            get {
                return ResourceManager.GetString("StartGameCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World generated!.
        /// </summary>
        public static string WorldGenerated {
            get {
                return ResourceManager.GetString("WorldGenerated", resourceCulture);
            }
        }
    }
}
