//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalLifeAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagicalLifeAPI.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crushing.
        /// </summary>
        internal static string Crushing {
            get {
                return ResourceManager.GetString("Crushing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirt.
        /// </summary>
        public static string Dirt {
            get {
                return ResourceManager.GetString("Dirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string Grass {
            get {
                return ResourceManager.GetString("Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvesting.
        /// </summary>
        public static string Harvesting {
            get {
                return ResourceManager.GetString("Harvesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvesting Skill.
        /// </summary>
        public static string HarvestingSkill {
            get {
                return ResourceManager.GetString("HarvestingSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string Human {
            get {
                return ResourceManager.GetString("Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic.
        /// </summary>
        internal static string Magic {
            get {
                return ResourceManager.GetString("Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maple Tree.
        /// </summary>
        public static string MapleTree {
            get {
                return ResourceManager.GetString("MapleTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Movement.
        /// </summary>
        public static string NormalMovement {
            get {
                return ResourceManager.GetString("NormalMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oak Tree.
        /// </summary>
        public static string OakTree {
            get {
                return ResourceManager.GetString("OakTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercing.
        /// </summary>
        internal static string Piercing {
            get {
                return ResourceManager.GetString("Piercing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pine Tree.
        /// </summary>
        public static string PineTree {
            get {
                return ResourceManager.GetString("PineTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison.
        /// </summary>
        internal static string Poison {
            get {
                return ResourceManager.GetString("Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone.
        /// </summary>
        public static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone.
        /// </summary>
        public static string StoneName {
            get {
                return ResourceManager.GetString("StoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Rubble.
        /// </summary>
        public static string StoneRubble {
            get {
                return ResourceManager.GetString("StoneRubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is dropped when stone is mined.
        /// </summary>
        public static string StoneRubbleDesc {
            get {
                return ResourceManager.GetString("StoneRubbleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilled Dirt.
        /// </summary>
        public static string TilledDirt {
            get {
                return ResourceManager.GetString("TilledDirt", resourceCulture);
            }
        }
    }
}
