using MagicalLifeAPI.DataTypes;
using MagicalLifeAPI.Entities;
using MagicalLifeAPI.Universal;
using Microsoft.Xna.Framework;
using ProtoBuf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MagicalLifeAPI.World
{
    /// <summary>
    /// Holds a section of the world.
    /// </summary>
    [ProtoContract]
    public class Chunk : Unique
    {
        [ProtoMember(1)]
        public List<Living> Creatures;

        [ProtoMember(2)]
        public ProtoArray<Tile> Tiles;

        [ProtoMember(3)]
        public Point ChunkLocation;

        /// <summary>
        /// The ID of what biome this chunk is generated by.
        /// </summary>
        [ProtoMember(4)]
        public string BiomeID;

        /// <summary>
        /// The width of this chunk in tiles.
        /// </summary>
        public static int Width = 20;

        /// <summary>
        /// The height of this chunk in tiles.
        /// </summary>
        public static int Height = 20;
    }
}
